# Generated by Django 5.2.11 on 2026-02-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('std_name', models.CharField(max_length=50)),
                ('std_age', models.IntegerField()),
            ],
        ),
    ]
